name: Manual Release

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    env:
      DATETIME: ""  # 显式声明变量（避免VSCode警告）

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        run: |
          zip -r all-pack.zip . -x "*.git*"

      - name: Get current datetime
        id: datetime-step
        run: |
          # 格式：YYYY-MM-DD_HH-MM-SS （24小时制，UTC时间）
          echo "DATETIME=$(date +'%Y-%m-%d)" >> $GITHUB_ENV
          echo "DATETIME=$(date +'%Y-%m-%d)" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "Release-${{ env.DATETIME }}"
          name: "Release-Pack-${{ env.DATETIME }}"
          body: |
            此 Rel 为 GitHub Actions 生成。
          files: all-pack.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}